import { useEffect, useMemo, useState } from "react";
import { generateBill, getHospitalAppointmentRequests, updateBillStatus } from "../services/api.js";
import "./Billing.css";

export default function Billing() {
  const [appointments, setAppointments] = useState([]), [appointmentId, setAppointmentId] = useState(""), [fee, setFee] = useState(""), [bill, setBill] = useState(null), [error, setError] = useState("");
  useEffect(() => { getHospitalAppointmentRequests().then(setAppointments).catch(e => setError(e.message)); }, []);
  const selected = useMemo(() => appointments.find(x => x.id === appointmentId), [appointments, appointmentId]);
  const create = async e => { e.preventDefault(); try { setBill(await generateBill({ appointment_id: appointmentId, manual_items: fee ? [{ description: "Consultation fee", quantity: 1, unit_price: Number(fee), total: 0 }] : [], tax_rate: 0 })); } catch (e) { setError(e.message); } };
  return <section className="page"><div className="page-header"><p className="eyebrow">Finance</p><h2>Billing</h2></div>{error && <div className="alert error">{error}</div>}<form className="hospital-panel no-print" onSubmit={create}><label className="field"><span>Appointment / patient</span><select required value={appointmentId} onChange={e => setAppointmentId(e.target.value)}><option value="">Select appointment</option>{appointments.map(x => <option value={x.id} key={x.id}>{x.doctorName} — {x.date}</option>)}</select></label>{selected && <p>Patient: {selected.patientName || "Selected appointment patient"}</p>}<label className="field"><span>Consultation fee</span><input type="number" min="0" value={fee} onChange={e => setFee(e.target.value)} /></label><button className="secondary-button">Generate bill</button></form>{bill && <article className="hospital-panel bill-print"><h2>MEDICHAIN INVOICE</h2><p>Bill #{bill.id}</p><p>Status: <select className="no-print" value={bill.status} onChange={async e => setBill(await updateBillStatus(bill.id, e.target.value))}>{["draft", "issued", "paid"].map(x => <option key={x}>{x}</option>)}</select></p><table><tbody>{bill.items.map((x, i) => <tr key={i}><td>{x.description}</td><td>{x.quantity}</td><td>₹{x.total}</td></tr>)}</tbody></table><p>Subtotal: ₹{bill.subtotal}</p><p>Tax: ₹{bill.tax}</p><h3>Total: ₹{bill.total}</h3><button className="secondary-button no-print" onClick={() => window.print()}>Print bill</button></article>}</section>;
}
